#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := OLED

#EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/import

include $(IDF_PATH)/make/project.mk
